language: node_js
sudo: false
node_js:
  - "6"

cache: yarn

scripts:
  - yarn lint
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
